import logging

FACE_ID = 'faceID'
REV_ID = 'revId'
ID = 'id'
DEBUGLEVEL = logging.NOTSET

NORMAL_MODE = 0x0
MINIMAL_MODE = 0x1
MORTISE_ALONG_LONGSIDE_MODE = 0x2
MORTISE_ALONG_SHORTSIDE_MODE = 0x4
FROMTOP_MODE = 0x8